{% set data= load_setup_py_data() %}
package:
  name: schedview
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/lsst/schedview
  git_rev: {{ CONDA_BUILD_TAG }}

build:
  entry_points:
    - prenight = schedview.app.prenight.prenight:main
    - scheduler_dashboard = schedview.app.scheduler_dashboard.scheduler_dashboard:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

test:
  requires:
    - pytest
    - pytest-cov
    - pytest-black
    - black
    - ruff
    - isort
    - python 
    - astropy >=5.3
    - bokeh >=3.1.1
    - colorcet
    - healpy
    - holoviews
    - hvplot
    - matplotlib
    - numpy {{ numpy }}
    - pandas
    - panel >=1.1.0
    - param
    - pytz
    - pyyaml
    - skyproj
    - uranography >=1.1.0
    - rubin-scheduler
    - rubin-sim >=2
  source_files:
    - schedview
    - tests
    - pyproject.toml
  commands:
    - prenight
    - scheduler_dashboard
    - pytest -vsx

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm_git_archive
    - setuptools {{ setuptools }}
    - setuptools_scm {{ setuptools_scm }}
  build:
    - python {{ python }}
    - pip
    - setuptools_scm_git_archive
    - setuptools {{ setuptools }}
    - setuptools_scm {{ setuptools_scm }}
    - numpy {{ numpy }}
  run:
    - python {{ python }}
    - astropy >=5.3
    - bokeh >=3.1.1
    - colorcet
    - healpy
    - holoviews
    - hvplot
    - matplotlib
    - numpy {{ numpy }}
    - pandas
    - panel >=1.1.0
    - param
    - pytz
    - pyyaml
    - skyproj
    - uranography >=1.1.0
    - rubin-scheduler >=3
    - rubin-sim >=2
