package:
  name: ts-develop
  version: 0.1.0

requirements:
  run:
    - aiokafka
    - astroquery
    - asynctest
    - black ==19.10b0
    - boto3
    - ephem
    - fontconfig
    - ginga
    - gitpython
    - ipdb
    - ipympl
    - jinja2
    - jsonschema
    - jupyter
    - kafkacat
    - lxml
    - moto
    - pre-commit
    - pycodestyle
    - pyqt
    - pytest
    - pytest-asyncio
    - pytest-black
    - pytest-cov
    - pytest-flake8
    - pytest-subtests
    - pytest-tornasync
    - pyyaml
    - setuptools
    - setuptools_scm
    - sqlalchemy
    - wget
