package:
  name: ts-develop
  version: 0.3.5

requirements:
  run:
    - aiokafka =0.7
    - astroquery =0.4
    - asynctest =0.13
    - black =20
    - ephem =4.1
    - ginga =3.2
    - ipdb =0.13
    - ipympl =0.8
    - jupyter =1
    - kafkacat =1.7
    - lxml =4.7
    - mypy =0.910
    - pre-commit =2.11
    - pyqt =5.12
    - pytest =6.2.4
    - pytest-asyncio =0.18
    - pytest-black =0.3
    - pytest-mypy =0.8
    - pytest-tornasync =0.6
    - rubin-env =0.7
    - setuptools_scm =6.4
    - types-PyYAML =5.4
    - wget =1.20
