package:
  name: ts-develop
  version: 0.3.4

requirements:
  run:
    - aiokafka =0.7
    - astroquery =0.4
    - asynctest =0.13
    - black =20
    - ephem =3
    - ginga =3.1
    - ipdb =0.13
    - ipympl =0.6
    - jupyter =1
    - kafkacat =1.4
    - lxml =4.6
    - mypy =0.812
    - pre-commit =2.10
    - pyqt =5.12
    - pytest-asyncio =0.14
    - pytest-black =0.3
    - pytest-mypy =0.8
    - pytest-tornasync =0.6
    - rubin-env =0.7
    - setuptools_scm =5.0
    - wget =1.20
