package:
  name: ts-conda-build
  version: 0.4.1

build:
  noarch: generic

requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}
  run:
    - astropy >=5
    - black =24
    - boto3 =1.34
    - flake8 =6
    - jsonschema =4
    - moto =5
    - mypy =1.9
    - numpy {{ numpy }}
    - pre-commit =3.6
    - py =1
    - pytest =8
    - pytest-asyncio =0.23
    - pytest-cov =4.1
    - python {{ python }}
    - pyyaml =6
    - setuptools {{ setuptools }}.*
    - setuptools_scm {{ setuptools_scm }}.*
    - types-pyyaml =6
