package:
  name: ts-conda-build
  version: 0.3.5

requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}
  run:
    - astropy >=5
    - asynctest =0.13
    - black =22
    - boto3 =1.22
    - jsonschema =3.2
    - moto =3
    - mypy =0.941
    - numpy {{ numpy }}
    - pre-commit =2.17
    - pytest =7
    - pytest-asyncio =0.18
    - pytest-black =0.3
    - pytest-cov =3.0
    - pytest-flake8 =1.0
    - pytest-mypy =0.8
    - pytest-tornasync =0.6
    - python {{ python }}
    - pyyaml =6.0
    - setuptools =62
    - setuptools_scm =6.4
    - types-pyyaml =6.0
