package:
  name: ts-conda-build
  version: 0.5.4

build:
  noarch: generic

requirements:
  host:
    - python {{ python }}
  build:
    - python {{ python }} # [build_platform != target_platform]
  run:
    - astropy >=5
    - boto3 =1.40
    - jsonschema =4
    - librdkafka =2.12
    - moto =5
    - numpy
    - pre-commit =4.3
    - py =1
    - pytest =8.4
    - pytest-asyncio =1.2
    - pytest-cov =7
    - python {{ python }}
    - python-confluent-kafka =2.12
    - pyyaml =6
    - types-pyyaml =6
