package:
  name: ts-conda-build
  version: 0.3.11

build:
  noarch: generic

requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}
  run:
    - astropy >=5
    - asynctest =0.13
    - black =23
    - boto3 =1.22
    - flake8 =4
    - jsonschema =3.2
    - moto =3
    - mypy =1.0.0
    - numpy {{ numpy }}
    - pre-commit =2.20
    - py =1
    - pytest =7
    - pytest-asyncio =0.20
    - pytest-black =0.3
    - pytest-cov =3.0
    - pytest-flake8 =1.0
    - pytest-mypy =0.8
    - pytest-tornasync =0.6
    - python {{ python }}
    - pyyaml =6.0
    - setuptools =65
    - setuptools_scm =7.0
    - ts-pre-commit-config =0.3
    - types-pyyaml =6.0
