package:
  name: ts-conda-build
  version: 0.4.0

build:
  noarch: generic

requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}
  run:
    - astropy >=5
    - asynctest =0.13
    - black =24
    - boto3 =1.34
    - flake8 =6
    - jsonschema =3.2
    - moto =5
    - mypy =1.9
    - numpy {{ numpy }}
    - pre-commit =3.6
    - py =1
    - pyaudio =0.2
    - pydub =0.25
    - pytest =8
    - pytest-asyncio =0.23
    - pytest-cov =4.1
    - pytest-tornasync =0.6
    - python {{ python }}
    - pyyaml =6
    - setuptools {{ setuptools }}.*
    - setuptools_scm {{ setuptools_scm }}.*
    - tornado =6.4
    - types-pyyaml =6
