{% set data = load_setup_py_data() %}
package:
  name: ts-tunablelaser
  version: {{data.get('version') }}

source:
  git_url: https://github.com/lsst-ts/ts_tunablelaser
  git_rev: develop

build:
  script: python -m pip install --ignore-installed --no-deps .
  skip: True # [win]

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - setuptools
    - setuptools_scm
    - argh
    - pyserial
    - ts-salobj

test:
  requires:
    - pytest
    - pytest-flake8
    - pytest-mock
    - pytest-cov
  commands:
    - py.test --pyargs lsst.ts.laser tests/
