{% set data= load_setup_py_data() %}
package:
  name: ts-xml
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/lsst-ts/ts_xml
  git_rev: develop

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
