{% set data= load_setup_py_data() %}
package:
  name: rubin-sim
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/lsst/rubin_sim
  git_rev: {{ CONDA_BUILD_TAG }}

build:
  noarch: python  
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - pytest
    - pytest-flake8
    - pytest-cov
    - pytest-black
    - astroplan
    - astropy
    - colorcet
    - h5py
    - healpy
    - matplotlib
    - numpy {{ numpy }}
    - openorb
    - openorb-data-de405
    - palpy
    - pandas
    - pytables
    - scikit-learn
    - scipy
    - sqlalchemy
    - sqlite
    - shapely
    - skyfield
    - tqdm
  source_files:
    - rubin_sim
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - rs_download_data
    - pytest -vsx

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm_git_archive
    - setuptools_scm
  build:
    - python {{ python }}
    - pip
    - setuptools_scm_git_archive
    - setuptools_scm
    - numpy {{ numpy }}
  run:
    - python {{ python }}
    - astroplan
    - astropy
    - colorcet
    - h5py
    - healpy
    - matplotlib
    - numpy {{ numpy }}
    - openorb
    - openorb-data-de405
    - palpy
    - pandas
    - pytables
    - scikit-learn
    - scipy
    - sqlalchemy
    - sqlite
    - shapely
    - skyfield
    - tqdm
    
