package:
  name: ts-develop
  version: 0.4.12

build:
  noarch: generic
  # Remove this when incrementing the version.
  # Or increment it if rebuilding 0.4.12
  number: 1

requirements:
  run:
    - aiohttp =3.11
    - aiokafka =0.12
    - aioserial =1.3
    - aiosqlite =0.21
    - asgi-lifespan =2
    - astroplan =0.10
    - astroquery =0.4
    - asyncpg =0.30
    - asyncqt =0.8
    - asynctest =0.13
    - batoid =0.8
    - black =25
    - control =0.10
    - crcmod =1.7
    - danish =0
    - documenteer =0.8.2
    # Here are the subpackages for documenteer
    # Out of order because easier to heirarchize
    - lsst-documenteer-pipelines
    - lsst-documenteer-guide
    - lsst-documenteer-technote
    - ephem =4.2
    - fastapi =0
    - ffmpeg =7
    - ginga =5.2
    - httpx =0.28
    - intelhex =2.3.0
    - ipdb =0.13
    - ipympl =0.9
    - jupyter =1
    - kafkacat =1.7
    - kafkit =0.2
    - lsst-efd-client =0.*
    - lxml =5
    - moto =5
    - mypy =1.15
    - paho-mqtt =2.1
    - pandas =2
    - parameterized =0.9
    - pigpio =1.78
    - postgresql =17
    - pre-commit =4.1
    - psycopg =3.2
    - py =1
    - pyasn1 =0.6
    - pyasn1-modules =0.4
    - pyaudio =0.2
    - pydantic =2
    - pydantic-settings =2
    - pydub =0.25
    - pylibftdi =0.20
    - pymodbus =3.8
    - pysnmp =7.1
    - pyside6 =6.8
    - pytest =8
    - pytest-asyncio =0.25
    - pytest-postgresql =6.0
    - pytest-tornasync =0.6
    - pytest-qt =4.4
    - pytest-xvfb =3.0
    - python-confluent-kafka =2
    - python-sounddevice =0.5
    - qasync =0.27
    - qt6-charts =6.8
    - rubin-env >=9
    - rubin-scheduler =3
    - setuptools_scm =8
    - slycot =0.*
    - smbus3 =0.5
    - sshtunnel =0.4
    - sphinx =6
    - sphinx-jsonschema =1.19
    - structlog =25.1
    - tornado =6.4
    - ts-pre-commit-config =0
    - types-pyyaml =6.0
    - types-python-dateutil =2
    - uvicorn =0.34
    - websockets =15
    - wget =1.21
    - yamllint =1.35
    - zaber-motion =7.4
    - zaber-serial =0.9
