package:
  name: ts-develop
  version: 0.3.11

requirements:
  run:
    - aiokafka =0.7
    - astroplan =0.8
    - astroquery =0.4
    - asynctest =0.13
    - black =22
    - ephem =4.1
    - ginga =3.4
    - ipdb =0.13
    - ipympl =0.9
    - jupyter =1
    - kafkacat =1.7
    - lxml =4.8
    - moto =3
    - mypy =0.991
    - pre-commit =2.20
    - pyqt =5.12
    - py =1
    - pytest =7
    - pytest-asyncio =0.20
    - pytest-black =0.3
    - pytest-mypy =0.8
    - pytest-tornasync =0.6
    - rubin-env >=0.7
    - setuptools_scm =7.0
    - types-pyyaml =6.0
    - wget =1.20
