package:
  name: ts-develop
  version: 0.4.9

build:
  noarch: generic

requirements:
  run:
    - aiohttp =3.9
    - aiokafka =0.10
    - aioserial =1.3
    - asgi-lifespan =2
    - astroplan =0.9
    - astroquery =0.4
    - asyncpg =0.29
    - asyncqt =0.8
    - asynctest =0.13
    - batoid =0.7
    - black =24
    - control =0.9
    - crcmod =1.7
    - danish =0
    - documenteer =0.8.2
    # Here are the subpackages for documenteer
    # Out of order because easier to heirarchize
    - lsst-documenteer-pipelines
    - lsst-documenteer-guide
    - lsst-documenteer-technote
    - ephem =4.1
    - fastapi =0.110
    - ffmpeg =6
    - ginga =4.0
    - httpx =0.27
    - intelhex =2.3.0
    - ipdb =0.13
    - ipympl =0.9
    - jupyter =1
    - kafkacat =1.7
    - kafkit =0.2
    - lsst-efd-client =0.*
    - lxml =5
    - moto =5
    - mypy =1.11
    - paho-mqtt =1.6
    - pandas =2
    - parameterized =0.9
    - postgresql =16
    - pre-commit =3.6
    - psycopg =3.1
    - py =1
    - pyaudio =0.2
    - pydantic =2
    - pydantic-settings =2
    - pydub =0.25
    - pylibftdi =0.20
    - pymodbus =3.6
    - pysnmp =4.4
    - pyside6 =6.7
    - pytest =8
    - pytest-asyncio =0.23
    - pytest-tornasync =0.6
    - pytest-postgresql =6.0
    - pytest-qt =4.4
    - pytest-xvfb =3.0
    - python-confluent-kafka =1.9
    - qasync =0.27
    - qt6-charts =6.7
    - rubin-env >=0.7
    - setuptools_scm =8.0
    - slycot =0.*
    - smbus3 =0.5
    - sshtunnel =0.4
    - sphinx =5
    - sphinx-jsonschema =1.19
    - structlog =24.2
    - tornado =6.4
    - ts-pre-commit-config =0
    - types-pyyaml =6.0
    - types-python-dateutil =2
    - uvicorn =0.28
    - websockets =12
    - wget =1.20
    - yamllint =1.35
    - zaber-motion =5.1
    - zaber-serial =0.9
