package:
  name: ts-develop
  version: 0.4.1

build:
  noarch: generic

requirements:
  run:
    - aiohttp =3.9
    - aiokafka =0.10
    - aioserial =1.3
    - asgi-lifespan =2
    - astroplan =0.9
    - astroquery =0.4
    - asyncpg =0.29
    - asyncqt =0.8
    - asynctest =0.13
    - batoid =0.6
    - black =24
    - control =0.9
    - danish =0.*
    - ephem =4.1
    - fastapi =0.110
    - ffmpeg =6
    - ginga =4.0
    - httpx =0.27
    - ipdb =0.13
    - ipympl =0.9
    - jupyter =1
    - kafkacat =1.7
    - kafkit =0.2
    - lsst-documenteer-guide =0.7
    - lsst-documenteer-pipelines =0.7
    - lsst-efd-client =0.*
    - lxml =5
    - moto =5
    - mypy =1.9
    - myst-parser =2.0
    - paho-mqtt =1.6
    - pandas =2
    - parameterized =0.9
    - postgresql =16
    - pre-commit =3.6
    - psycopg =3.1
    - py =1
    - pyaudio =0.2
    - pydantic =2
    - pydantic-settings =2
    - pydub =0.25
    - pylibftdi =0.20
    - pymodbus =3.6
    - pyside2 =5.15
    - pytest =8
    - pytest-asyncio =0.23
    - pytest-tornasync =0.6
    - pytest-postgresql =6.0
    - pytest-qt =4.4
    - pytest-xvfb =3.0
    - python-confluent-kafka =1.9
    - qasync =0.27
    - rubin-env >=0.7
    - setuptools_scm =8.0
    - slycot =0.*
    - sshtunnel =0.4
    - sphinx-jsonschema =1.19
    - tornado =6.4
    - ts-pre-commit-config =0.*
    - types-pyyaml =6.0
    - types-python-dateutil =2
    - uvicorn =0.28
    - websockets =12
    - wget =1.20
    - yamllint =1.35
    - zaber-motion =5.1
    - zaber-serial =0.9
