package:
  name: ts-develop
  version: 0.3.22

build:
  noarch: generic

requirements:
  run:
    - aiohttp >=3.8
    - aiokafka =0.7
    - aioserial =1.3
    - astroplan =0.8
    - astroquery =0.4
    - asyncqt =0.8
    - asynctest =0.13
    - black =23
    - ephem =4.1
    - ginga =3.4
    - ipdb =0.13
    - ipympl =0.9
    - jupyter =1
    - jupyterlab >=3.5
    - kafkacat =1.7
    - kafkit =0.2
    - lsst-documenteer-guide =0.7
    - lsst-documenteer-pipelines =0.7
    - lxml =4.9
    - moto =3
    - mypy =1.2.0
    - myst-parser =0.18
    - paho-mqtt =1.6
    - pandas =1.5
    - parameterized =0.9
    - pre-commit =3.0
    - py =1
    - pylibftdi =0.20
    - pymodbus =3.1
    - pyside2 =5.15
    - pytest =7
    - pytest-asyncio =0.20
    - pytest-black =0.3
    - pytest-mypy =0.8
    - pytest-tornasync =0.6
    - pytest-qt =4.2
    - pytest-xvfb =2.0
    - python-confluent-kafka =1.9
    - qasync =0.23
    - rubin-env >=0.7
    - setuptools_scm =7.0
    - sshtunnel =0.4
    - sphinx-jsonschema =1.19
    - ts-pre-commit-config =0.4
    - types-pyyaml =6.0
    - wget =1.20
    - yamllint =1.31
    - zaber-serial =0.9
