{% set version = "0.6.1" %}

package:
  name: centralized-pre-commit-conf
  version: {{ version }}

source:
  git_url: https://github.com/Pierre-Sassoulas/centralized-pre-commit-conf
  git_rev: v{{ version }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - pre-commit-conf = centralized_pre_commit_conf.main:run

test:
  requires:
    - pytest-cov
    - pytest-vcr
    - python-coveralls
    - coverage
    - coveralls
    - pylint =2.15.4
  source_files:
    - tests
  commands:
    - pytest

requirements:
  host:
    - python
    - setuptools
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools >=45.1
    - wheel >=0.34
    - colorama
    - confuse
    - pre-commit >=1.16
    - requests

about:
  author : Pierre Sassoulas
  author_email : pierre.sassoulas@gmail.com
  home: https://github.com/Pierre-Sassoulas/centralized-pre-commit-conf
  summary: Centralized pre-commit hooks.
  description: |
    Easily install and update centralized pre-commit hooks and their
    configuration files in decentralized repositories.
  dev_url: https://github.com/shibukawa/imagesize_py
  doc_source_url: https://github.com/Pierre-Sassoulas/centralized-pre-commit-conf/blob/master/README.md
  license: MIT
  license_file: LICENSE
