{% set data= load_setup_py_data() %}
package:
  name: ts-idl
  version: {{ data.get('version') }}_{{ TS_XML_VERSION }}

source:
  git_url: https://github.com/lsst-ts/ts_idl
  git_rev: v1.1.0

build:
  skip: False #[win]
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - LSST_SDK_INSTALL
    - OSPL_HOME
    - LSST_DDS_DOMAIN
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
  run:
    - python
    - setuptools
    - setuptools_scm
