package:
  name: ts-conda-build
  version: 0.2.0

requirements:
  run:
    - astropy =4.1
    - asynctest =0.13
    - black =19.10b0
    - boto3 =1.16
    - jsonschema =3.2
    - moto =1.3
    - numpy =1.20
    - pre-commit =2.8
    - pytest =6.2
    - pytest-asyncio =0.14
    - pytest-black =0.3
    - pytest-cov =2.10
    - pytest-flake8 =1.0
    - pytest-tornasync =0.6
    - python =3.8
    - pyyaml =5.1
    - setuptools =49.6
    - setuptools_scm =4.1
