package:
  name: ts-conda-build
  version: 0.3.4

requirements:
  run:
    - astropy >=5
    - asynctest =0.13
    - black =22
    - boto3 =1.21
    - jsonschema =3.2
    - moto =3
    - mypy =0.941
    - numpy =1.20
    - pre-commit =2.17
    - pytest =7
    - pytest-asyncio =0.18
    - pytest-black =0.3
    - pytest-cov =3.0
    - pytest-flake8 =1.0
    - pytest-mypy =0.8
    - pytest-tornasync =0.6
    - python =3.8
    - pyyaml =6.0
    - setuptools =60.9
    - setuptools_scm =6.4
    - types-pyyaml =6.0
